option("threads", function()
  set_showmenu(true)
  set_description("verilator running threads")
  set_default("16")
end)

option("dramsim", function()
  set_showmenu(true)
  set_description("compile with dramsim3")
  set_default(false)
end)

option("dramsim-home", function()
  set_showmenu(true)
  set_description("dramsim3 home path")
  set_default("")
end)

option("ref-model", function()
  set_showmenu(true)
  set_description("difftest reference model")
  set_default("Spike")
end)

option("volatile-chisel", function()
  set_showmenu(true)
  set_description("every time run simulation compilation, regenerate the rtl")
  set_default(false)
end)
